<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Test_Suite" duration-ms="78" started-at="2015-09-24T19:42:23Z" finished-at="2015-09-24T19:42:23Z">
    <groups>
    </groups>
    <test name="Test_Cases" duration-ms="78" started-at="2015-09-24T19:42:23Z" finished-at="2015-09-24T19:42:23Z">
      <class name="Appium_PKG.NewTest1">
        <test-method status="FAIL" signature="test_method_TestNG()[pri:0, instance:Appium_PKG.NewTest1@1ef7fe8e]" name="test_method_TestNG" duration-ms="8" started-at="2015-09-25T01:12:23Z" finished-at="2015-09-25T01:12:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at Appium_PKG.NewTest1.test_method_TestNG(NewTest1.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_method_TestNG -->
      </class> <!-- Appium_PKG.NewTest1 -->
      <class name="Appium_PKG.NewTest">
        <test-method status="PASS" signature="testforTestNG()[pri:0, instance:Appium_PKG.NewTest@629f0666]" name="testforTestNG" duration-ms="28" started-at="2015-09-25T01:12:23Z" finished-at="2015-09-25T01:12:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testforTestNG -->
      </class> <!-- Appium_PKG.NewTest -->
    </test> <!-- Test_Cases -->
  </suite> <!-- Test_Suite -->
</testng-results>
